image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
matrix:
  fast_finish: true
cache:
  - c:\tools\vcpkg\installed\
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  - cd c:\tools\vcpkg
  - git pull
  - vcpkg update
  - vcpkg upgrade --no-dry-run
  - vcpkg integrate install

  - vcpkg --triplet x64-windows install glm glfw3 sfml glbinding

before_build:
  - cd C:\projects\swarmmind-client
  - mkdir build && cd build
  - cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_PREFIX_PATH=C:\deps\glbinding -DBOOST_ROOT=C:\Libraries\boost_1_67_0 -G "Visual Studio 15 2017 Win64" ..
build:
  project: build\SwarmMind-Client.sln
  verbosity: minimal
  parallel: true
  
after_build:
  - ps: cd C:\projects\swarmmind-client
  - mkdir package
  - ps: cp build\src\$env:CONFIGURATION\SwarmMind-Client.exe package
  - ps: cp -r -v fonts package
  - ps: cp -r -v shaders package
  - ps: cp -r -v sound package
  - ps: cp -r -v res package
  - ps: cp -r -v build\src\$env:CONFIGURATION\*.dll package

artifacts:
  - path: package
    name: SwarmMind_Client
    type: zip
