image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
cache:
  - C:\projects\glfw
  - C:\projects\glbinding
  - C:\projects\glm
  - C:\projects\sioclient
  - C:\projects\build-glfw -> appveyor.yml
  - C:\projects\build-glbinding -> appveyor.yml
  - C:\projects\build-glm -> appveyor.yml
  - C:\projects\build-sioclient -> appveyor.yml
install:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

  - git clone --depth 1 https://github.com/glfw/glfw.git C:\projects\glfw
  - cd C:\projects\glfw
  - git fetch --depth 1 --tags
  - git checkout 3.2.1
  - cd .. && mkdir build-glfw && cd build-glfw
  - cmake \
    -DCMAKE_BUILD_TYPE=%CONFIGURATION% \
    -DCMAKE_INSTALL_PREFIX=C:\deps\glfw \
    -G "Visual Studio 15 2017 Win64" \
    ../glfw
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target install

  - git clone --depth 1 https://github.com/g-truc/glm.git C:\projects\glm
  - cd C:\projects\glm
  - git fetch --depth 1 --tags
  - git checkout 0.9.9.0
  - cd .. && mkdir build-glm && cd build-glm
  - cmake \
    -DCMAKE_BUILD_TYPE=%CONFIGURATION% \
    -DCMAKE_INSTALL_PREFIX=C:\deps\glm \
    -DGLM_INSTALL_ENABLE=true \
    -G "Visual Studio 15 2017 Win64" \
    ../glm
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target install

  - git clone --depth 1 https://github.com/cginternals/glbinding C:\projects\glbinding
  - cd C:\projects\glbinding
  - git fetch --depth 1 --tags
  - git checkout v2.1.4
  - cd .. && mkdir build-glbinding && cd build-glbinding
  - cmake \
    -DCMAKE_BUILD_TYPE=%CONFIGURATION% \
    -DCMAKE_INSTALL_PREFIX=C:\deps\glbinding \
    -DCMAKE_CXX_FLAGS="/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING /EHsc" \
    -DCMAKE_PREFIX_PATH=C:\deps\glfw \
    -G "Visual Studio 15 2017 Win64" \
    ../glbinding
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target install

  - git clone --depth 1 --branch fixes https://github.com/SwarmMind/socket.io-client-cpp.git C:\projects\sioclient
  - cd C:\projects\sioclient
  - git fetch --depth 1 --tags
  - cd .. && mkdir build-sioclient && cd build-sioclient
  - cmake \
    -DCMAKE_BUILD_TYPE=%CONFIGURATION% \
    -DCMAKE_INSTALL_PREFIX=C:\deps\sioclient \
    -DCMAKE_CXX_FLAGS="/D_SCL_SECURE_NO_WARNINGS /EHsc" \
    -DBOOST_ROOT=C:\Libraries\boost_1_67_0 \
    -DBOOST_VER=1.67.0 \
    -G "Visual Studio 15 2017 Win64" \
    ../sioclient
  - cmake --build . --config %CONFIGURATION%
  - cmake --build . --config %CONFIGURATION% --target install

before_build:
  - cd C:\projects\swarmmind-client
  - mkdir build && cd build
  - cmake \
    -DCMAKE_BUILD_TYPE=%CONFIGURATION% \
    -DCMAKE_PREFIX_PATH=C:\deps\glfw;C:\deps\glbinding;C:\deps\sioclient \
    -DSIOCLIENT_USE_FIND_PACKAGE=ON \
    -G "Visual Studio 15 2017 Win64" \
    ..
build:
  project: build\SwarmMind-Client.sln
#  verbosity: minimal
  parallel: true
artifacts:
  - path: build
    name: Build output
    type: zip
