image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
cache:
  - C:\projects\glfw
  - C:\projects\glbinding
  - C:\projects\glm
install:
  - git clone --depth 1 https://github.com/glfw/glfw.git C:\projects\glfw
  - cd C:\projects\glfw
  - git fetch --depth 1 --tags
  - git checkout 3.2.1
  - cd .. && mkdir build-glfw && cd build-glfw
  - cmake \
    -DCMAKE_INSTALL_PREFIX=C:\deps\glfw \
    -G "Visual Studio 15 2017 Win64" \
    ../glfw
  - cmake --build .
  - cmake --build . --target install

  - git clone --depth 1 https://github.com/g-truc/glm.git C:\projects\glm
  - cd C:\projects\glm
  - git fetch --depth 1 --tags
  - git checkout 0.9.9.0
  - cd .. && mkdir build-glm && cd build-glm
  - cmake \
    -DCMAKE_INSTALL_PREFIX=C:\deps\glm \
    -DGLM_INSTALL_ENABLE=true \
    -G "Visual Studio 15 2017 Win64" \
    ../glm
  - cmake --build .
  - cmake --build . --target install

  - git clone --depth 1 https://github.com/cginternals/glbinding C:\projects\glbinding
  - cd C:\projects\glbinding
  - git fetch --depth 1 --tags
  - git checkout v2.1.4
  - cd .. && mkdir build-glbinding && cd build-glbinding
  - cmake \
    -DCMAKE_CXX_FLAGS=/D_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING \
    -DCMAKE_PREFIX_PATH=C:\deps\glfw \
    -DCMAKE_INSTALL_PREFIX=C:\deps\glbinding \
    -G "Visual Studio 15 2017 Win64" \
    ../glbinding
  - cmake --build .
  - cmake --build . --target install

  - git clone --depth 1 --branch fixes https://github.com/SwarmMind/socket.io-client-cpp.git C:\projects\sioclient
  - cd C:\projects\sioclient
  - git fetch --depth 1 --tags
  - cd .. && mkdir build-sioclient && cd build-sioclient
  - cmake \
    -DCMAKE_INSTALL_PREFIX=C:\deps\sioclient \
    -DBOOST_ROOT=C:\Libraries\boost_1_67_0 \
    -DBOOST_VER=1.67.0 \
    -DCMAKE_CXX_FLAGS=/D_SCL_SECURE_NO_WARNINGS \
    -G "Visual Studio 15 2017 Win64" \
    ../sioclient
  - cmake --build .
  - cmake --build . --target install

before_build:
  - cmd: |
      cd C:\projects\swarmmind-client
      mkdir build
      cd build
      cmake --version
      cmake -Dglfw3_DIR=C:\deps\glfw -Dglbinding_DIR=C:\deps\glbinding -DSIOCLIENT_DIR=C:\deps\sioclient -G "Visual Studio 15 2017 Win64" ..
build:
  project: build\SwarmMind.sln
#  verbosity: minimal
  parallel: true
artifacts:
  - path: build
    name: Build output
    type: zip
