image:
  - Visual Studio 2017
configuration:
  - Release
  - Debug
install:
  - git clone --depth 1 https://github.com/glfw/glfw.git C:\projects\glfw
  - cd C:\projects\glfw
  - git fetch --depth 1 --tags
  - git checkout 3.2.1
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_DIR=C:\deps\glfw -G "Visual Studio 15 2017 Win64"
  - cmake --build .

  - git clone --depth 1 https://github.com/g-truc/glm.git C:\projects\glm
  - cd C:\projects\glm
  - git fetch --depth 1 --tags
  - git checkout 0.9.9.0

  - git clone --depth 1 https://github.com/cginternals/glbinding C:\projects\glbinding
  - cd C:\projects\glbinding
  - git fetch --depth 1 --tags
  - git checkout v2.1.4
  - mkdir build && cd build
  - cmake .. -DCMAKE_INSTALL_DIR=C:\deps\glbinding -G "Visual Studio 15 2017 Win64"
  - cmake --build .
before_build:
  - cmd: |
      mkdir build
      cd build
      cmake --version
      cmake .. -DGLFW_DIR=C:\deps\glfw -G "Visual Studio 15 2017 Win64"
build:
  project: build\SwarmMind.sln
#  verbosity: minimal
  parallel: true

