language: cpp
compiler:
    - clang
    - gcc
install:
    - git clone https://github.com/socketio/socket.io-client-cpp.git sioclient
    - mkdir build-sioclient && cd build-sioclient
    - cmake \
        -DBUILD_SHARED_LIBS=ON \
        -DCMAKE_BUILD_TYPE=Release \
        -DCMAKE_INSTALL_PREFIX=/usr \
        "../sioclient"
    - make && sudo make install

script:
    - mkdir build && cd build
    - cmake \
        -DSIOCLIENT_USE_FIND_PACKAGE=ON \
        -DCMAKE_PREFIX_PATH=../thirdparty \
        -DCMAKE_BUILD_TYPE=Release \
        ..
    - make
